// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA924HsR-IQ1Ck8K-Dld3cY9dqyrWptGr8',
    appId: '1:508615971640:web:a71b8fc8e38a64e6a827cd',
    messagingSenderId: '508615971640',
    projectId: 'coilcity',
    authDomain: 'coilcity.firebaseapp.com',
    storageBucket: 'coilcity.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaytFBD9gL-0qQBfpNPQvU5eXefKWNqtU',
    appId: '1:508615971640:android:73b7d97e266ae9c0a827cd',
    messagingSenderId: '508615971640',
    projectId: 'coilcity',
    storageBucket: 'coilcity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr610lQTropO28Z6SiTK-bWfb2LCPW1_0',
    appId: '1:508615971640:ios:fa5ad917c8fb0f2ea827cd',
    messagingSenderId: '508615971640',
    projectId: 'coilcity',
    storageBucket: 'coilcity.firebasestorage.app',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr610lQTropO28Z6SiTK-bWfb2LCPW1_0',
    appId: '1:508615971640:ios:fa5ad917c8fb0f2ea827cd',
    messagingSenderId: '508615971640',
    projectId: 'coilcity',
    storageBucket: 'coilcity.firebasestorage.app',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA924HsR-IQ1Ck8K-Dld3cY9dqyrWptGr8',
    appId: '1:508615971640:web:d83bb270ac9069c7a827cd',
    messagingSenderId: '508615971640',
    projectId: 'coilcity',
    authDomain: 'coilcity.firebaseapp.com',
    storageBucket: 'coilcity.firebasestorage.app',
  );
}
